spring:
  application:
    name: EduQuest

# jWT security
eduquest:
  app:
    jwtSecret: PasswordSuperMoltoLungaEComplicatissimaCheNessunoPuoIndovinare123!
    jwtExpirationMs: 86400000

# cloudinary
cloudinary:
  cloud_name: duh7h2j8v
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}