app:
  default:
    password: "0000"
    username: "test_student"

spring:
  application:
    name: EduQuest
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:eduquestdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
      resources:
        cache:
          period: 0
        static-locations: classpath:/static/
  thymeleaf:
    cache: false

# JWT security
eduquest:
  app:
    jwtSecret: PasswordSuperMoltoLungaEComplicatissimaCheNessunoPuoIndovinare123!
    jwtExpirationMs: 86400000

# Cloudinary
cloudinary:
  cloud_name: dkxvumxu5
  api_key: 637885348811393
  api_secret: I3PJfZzbb8XQcfbIQ4vxrsvdUxA