spring:
  application:
    name: EduQuest

# Configurazione limiti Upload
	servlet:
	  multipart:
	    max-file-size: 10MB
	    max-request-size: 10MB
		  
# jWT security
eduquest:
  app:
    jwtSecret: PasswordSuperMoltoLungaEComplicatissimaCheNessunoPuoIndovinare123!
    jwtExpirationMs: 86400000

# cloudinary
cloudinary:
  cloud_name: dkxvumxu5
  api_key: 637885348811393
  api_secret: I3PJfZzbb8XQcfbIQ4vxrsvdUxA