spring:
  application:
    name: EduQuest

# jWT security
eduquest:
  app:
    jwtSecret: PasswordSuperMoltoLungaEComplicatissimaCheNessunoPuoIndovinare123!
    jwtExpirationMs: 86400000

# cloudinary
cloudinary:
  cloud_name: duh7h2j8v
  api_key: 899276221797397
  api_secret: cQnQwrxo4J7tMgKQQyFMNmnyGNU