name: SonarCloud Frontend
on:
  push:
    branches: [ "main", "develop", "frontend-services-refactoring" ]
    paths:
      - 'src/main/resources/static/**'

jobs:
  sonarcloud-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/main/resources/static

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: src/main/resources/static 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONTEND }}